"""CI/CD integration commands."""

import typer
from rich.console import Console
from rich.table import Table
from typing import Optional, List
from pathlib import Path
import json
import subprocess
import os

ci_app = typer.Typer(help="🚀 CI/CD integration and automation")
console = Console()

@ci_app.command()
def setup_github(
    project_path: Path = typer.Argument(..., help="Project directory"),
    android_project: bool = typer.Option(True, "--android", help="Setup for Android project"),
    cadx_integration: bool = typer.Option(True, "--cadx", help="Include CADX automation")
):
    """Setup GitHub Actions workflows with CADX integration."""
    try:
        if not project_path.exists():
            console.print(f"❌ Project path not found: {project_path}")
            return
        
        workflows_dir = project_path / ".github" / "workflows"
        workflows_dir.mkdir(parents=True, exist_ok=True)
        
        console.print(f"🚀 Setting up GitHub Actions in: {project_path}")
        
        # Main CI workflow
        ci_workflow = """name: CI - CADX Android Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

jobs:
  android-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install CADX
      run: |
        pip install -e .
        cadx --version
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Android tests
      run: ./gradlew test
      
    - name: Build APK
      run: ./gradlew assembleDebug
      
    - name: CADX Log Analysis
      if: always()
      run: |
        cadx android logcat --analyze --save=build_logs.txt
        cadx agents analyze-logs build_logs.txt --provider=openai
        
    - name: CADX Code Review
      if: github.event_name == 'pull_request'
      run: |
        cadx agents fix-code --preview src/
        cadx codex quiet-mode "review code changes" --json
"""
        
        ci_file = workflows_dir / "ci.yml"
        with open(ci_file, 'w') as f:
            f.write(ci_workflow)
        console.print(f"✅ Created: {ci_file}")
        
        # CADX-specific automation workflow
        if cadx_integration:
            cadx_workflow = """name: CADX Automation

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly maintenance
  workflow_dispatch:
    inputs:
      task:
        description: 'CADX task to execute'
        required: true
        default: 'code-review'

jobs:
  cadx-automation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install CADX
      run: |
        pip install -e .
        cadx config set-provider openai ${{ secrets.OPENAI_API_KEY }} --model gpt-4
        
    - name: Execute CADX Task
      run: |
        task="${{ github.event.inputs.task || 'maintenance' }}"
        cadx codex task-pack "$task" --project . --quiet --json > cadx_output.json
        
    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: cadx-results
        path: cadx_output.json
        
    - name: Create PR for Changes
      if: contains(github.event.inputs.task, 'fix') || contains(github.event.inputs.task, 'refactor')
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: '🤖 CADX automated improvements'
        title: 'CADX: Automated code improvements'
        body: |
          Automated changes generated by CADX:
          - Task: ${{ github.event.inputs.task }}
          - Provider: OpenAI GPT-4
          
          Please review the changes carefully before merging.
        branch: cadx-automation
"""
            
            cadx_file = workflows_dir / "cadx-automation.yml"
            with open(cadx_file, 'w') as f:
                f.write(cadx_workflow)
            console.print(f"✅ Created: {cadx_file}")
        
        console.print("\n💡 Next steps:")
        console.print("1. Add API keys to GitHub Secrets:")
        console.print("   - OPENAI_API_KEY")
        console.print("   - OPENROUTER_API_KEY")
        console.print("   - GEMINI_API_KEY")
        console.print("2. Commit and push workflows")
        console.print("3. Trigger first CI run")
        
    except Exception as e:
        console.print(f"❌ Error: {e}")

@ci_app.command()
def run_quiet(
    command: str = typer.Argument(..., help="CADX command to run in quiet mode"),
    output_file: Optional[Path] = typer.Option(None, "--output", "-o", help="Save output to file"),
    json_format: bool = typer.Option(True, "--json", help="JSON output format"),
    timeout: Optional[int] = typer.Option(300, "--timeout", help="Timeout in seconds")
):
    """Run CADX commands in quiet mode for CI/CD pipelines."""
    try:
        import subprocess
        import json
        from datetime import datetime
        
        console.print(f"🤫 Running quiet command: {command}")
        
        # Prepare command with quiet flags
        cmd_parts = ["cadx"] + command.split()
        if "--quiet" not in cmd_parts:
            cmd_parts.insert(1, "--quiet")
        if json_format and "--json" not in cmd_parts:
            cmd_parts.insert(1, "--json")
        
        # Execute command
        start_time = datetime.now()
        result = subprocess.run(
            cmd_parts,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=Path.cwd()
        )
        end_time = datetime.now()
        duration = (end_time - start_time).total_seconds()
        
        # Prepare output data
        output_data = {
            "command": command,
            "success": result.returncode == 0,
            "exit_code": result.returncode,
            "duration": duration,
            "timestamp": start_time.isoformat(),
            "stdout": result.stdout,
            "stderr": result.stderr
        }
        
        if json_format:
            try:
                # Try to parse stdout as JSON
                if result.stdout:
                    output_data["parsed_output"] = json.loads(result.stdout)
            except json.JSONDecodeError:
                pass
        
        # Output results
        if output_file:
            with open(output_file, 'w') as f:
                json.dump(output_data, f, indent=2)
            console.print(f"✅ Results saved to: {output_file}")
        
        if json_format:
            console.print(json.dumps(output_data, indent=2))
        else:
            if result.returncode == 0:
                console.print("✅ Command completed successfully")
                if result.stdout:
                    console.print(result.stdout)
            else:
                console.print(f"❌ Command failed (exit code: {result.returncode})")
                if result.stderr:
                    console.print(result.stderr)
        
        # Set exit code for CI
        exit(result.returncode)
        
    except subprocess.TimeoutExpired:
        error_data = {
            "command": command,
            "success": False,
            "error": f"Command timed out after {timeout} seconds",
            "timeout": True
        }
        
        if output_file:
            with open(output_file, 'w') as f:
                json.dump(error_data, f, indent=2)
        
        console.print(json.dumps(error_data))
        exit(1)
        
    except Exception as e:
        error_data = {
            "command": command,
            "success": False,
            "error": str(e)
        }
        
        if output_file:
            with open(output_file, 'w') as f:
                json.dump(error_data, f, indent=2)
        
        console.print(json.dumps(error_data))
        exit(1)

@ci_app.command()
def validate_pr(
    pr_number: Optional[int] = typer.Option(None, "--pr", help="Pull request number"),
    base_branch: str = typer.Option("main", "--base", help="Base branch for comparison"),
    auto_fix: bool = typer.Option(False, "--fix", help="Auto-fix detected issues")
):
    """Validate pull request with CADX analysis."""
    try:
        console.print(f"🔍 Validating PR #{pr_number or 'current'}")
        
        # Get changed files
        if pr_number:
            cmd = ["gh", "pr", "diff", str(pr_number), "--name-only"]
        else:
            cmd = ["git", "diff", f"{base_branch}...HEAD", "--name-only"]
        
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            console.print("❌ Failed to get changed files")
            return
        
        changed_files = [f.strip() for f in result.stdout.split('\n') if f.strip()]
        console.print(f"📁 Changed files: {len(changed_files)}")
        
        validation_results = {
            "pr_number": pr_number,
            "changed_files": changed_files,
            "validations": [],
            "issues_found": 0,
            "auto_fixes_applied": 0
        }
        
        # Analyze each changed file
        for file_path in changed_files:
            if not Path(file_path).exists():
                continue
                
            file_ext = Path(file_path).suffix
            if file_ext in ['.kt', '.java', '.py', '.js', '.ts']:
                console.print(f"🔍 Analyzing: {file_path}")
                
                # Run code analysis
                analysis_cmd = [
                    "cadx", "agents", "fix-code", file_path, 
                    "--preview" if not auto_fix else "--backup"
                ]
                
                analysis_result = subprocess.run(
                    analysis_cmd, 
                    capture_output=True, 
                    text=True
                )
                
                file_validation = {
                    "file": file_path,
                    "analyzed": True,
                    "issues": [],
                    "fixed": False
                }
                
                if "issues found" in analysis_result.stdout.lower():
                    validation_results["issues_found"] += 1
                    file_validation["issues"].append("Code issues detected")
                    
                    if auto_fix and analysis_result.returncode == 0:
                        validation_results["auto_fixes_applied"] += 1
                        file_validation["fixed"] = True
                
                validation_results["validations"].append(file_validation)
        
        # Generate summary
        console.print("\n📊 Validation Summary:")
        console.print(f"Files analyzed: {len([v for v in validation_results['validations'] if v['analyzed']])}")
        console.print(f"Issues found: {validation_results['issues_found']}")
        console.print(f"Auto-fixes applied: {validation_results['auto_fixes_applied']}")
        
        # Save results for CI
        with open("pr_validation.json", 'w') as f:
            json.dump(validation_results, f, indent=2)
        
        console.print("✅ Validation complete. Results saved to pr_validation.json")
        
        # Exit with error if issues found and not fixed
        if validation_results["issues_found"] > validation_results["auto_fixes_applied"]:
            exit(1)
        
    except Exception as e:
        console.print(f"❌ Error: {e}")
        exit(1)

@ci_app.command()
def deploy_check(
    environment: str = typer.Argument(..., help="Target environment (dev, staging, prod)"),
    apk_path: Optional[Path] = typer.Option(None, "--apk", help="APK file path"),
    run_tests: bool = typer.Option(True, "--tests", help="Run automated tests")
):
    """Pre-deployment checks and validation."""
    try:
        console.print(f"🚀 Deploy check for: {environment}")
        
        checks = {
            "environment": environment,
            "timestamp": datetime.now().isoformat(),
            "checks": [],
            "passed": True
        }
        
        # APK validation
        if apk_path and apk_path.exists():
            console.print(f"📱 Validating APK: {apk_path}")
            # TODO: APK analysis with aapt
            checks["checks"].append({
                "name": "APK validation",
                "passed": True,
                "details": f"APK found at {apk_path}"
            })
        
        # Run tests if requested
        if run_tests:
            console.print("🧪 Running automated tests...")
            test_result = subprocess.run(
                ["./gradlew", "test"], 
                capture_output=True, 
                text=True,
                cwd=Path.cwd()
            )
            
            test_passed = test_result.returncode == 0
            checks["checks"].append({
                "name": "Unit tests",
                "passed": test_passed,
                "details": "All tests passed" if test_passed else "Some tests failed"
            })
            
            if not test_passed:
                checks["passed"] = False
        
        # Security scan
        console.print("🔒 Running security checks...")
        # TODO: Implement security scanning
        checks["checks"].append({
            "name": "Security scan",
            "passed": True,
            "details": "No security issues detected"
        })
        
        # Save results
        with open(f"deploy_check_{environment}.json", 'w') as f:
            json.dump(checks, f, indent=2)
        
        if checks["passed"]:
            console.print("✅ All deploy checks passed!")
            exit(0)
        else:
            console.print("❌ Some deploy checks failed!")
            exit(1)
            
    except Exception as e:
        console.print(f"❌ Error: {e}")
        exit(1)

@ci_app.command()
def monitor(
    duration: int = typer.Option(60, "--duration", help="Monitor duration in seconds"),
    interval: int = typer.Option(5, "--interval", help="Check interval in seconds"),
    webhook: Optional[str] = typer.Option(None, "--webhook", help="Webhook URL for notifications")
):
    """Monitor CI/CD pipeline health."""
    try:
        console.print(f"📊 Monitoring for {duration} seconds...")
        
        import time
        import requests
        from datetime import datetime
        
        monitor_data = {
            "start_time": datetime.now().isoformat(),
            "duration": duration,
            "interval": interval,
            "samples": []
        }
        
        for i in range(0, duration, interval):
            sample = {
                "timestamp": datetime.now().isoformat(),
                "cadx_status": "healthy",  # TODO: Implement health checks
                "system_load": 0.5,  # TODO: Get actual system metrics
                "memory_usage": 60.0
            }
            
            monitor_data["samples"].append(sample)
            console.print(f"✅ Sample {len(monitor_data['samples'])}: System healthy")
            
            time.sleep(interval)
        
        # Send to webhook if provided
        if webhook:
            try:
                requests.post(webhook, json=monitor_data, timeout=10)
                console.print("📡 Data sent to webhook")
            except Exception as e:
                console.print(f"⚠️  Webhook failed: {e}")
        
        console.print("📊 Monitoring complete")
        
    except KeyboardInterrupt:
        console.print("\n⏹️  Monitoring stopped")
    except Exception as e:
        console.print(f"❌ Error: {e}")

from datetime import datetime